# Generated by Django 4.1.5 on 2023-01-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='useremail',
            new_name='user_email',
        ),
    ]
